### ISSUE TITLE
Freshdesk New API Syntax: "Embedding"

### ISSUE THREAD

**Issue by indiesk** [singer-io/tap-freshdesk#16]
According to [Freshdesk's API Documentation](https://developers.freshdesk.com/api/#embedding), the information about the requester of a ticket is not included in the response anymore by default.

> Our previous version of APIs returned a large number of fields by default. In order to increase performance and reduce data usage, we have removed several of these fields in our v2.0 APIs. For example, when you view a ticket, we no longer return the requester's name or the company name.

But they still seem to provide a way to retrieve the information:

> You can request for additional resources using the "include" keyword. For example you can embed the requester's details within the ticket view API by using the following command:

```
/api/v2/tickets/[id]?include=requester
```

This [link](https://developers.freshdesk.com/api/#view_a_ticket) gives a detailed information about the "**embedding**" feature.

I wasn't sure if the current version takes this into consideration? I haven't been able to retrieve the full data of the tickets from the tables replicated through Stitch Data.

Thank you!

**Comment by nick-mccoy** [comment]
Thanks for catching this!  We'll take a look, do some testing, and try to get this resolved within the next week or two.

**Comment by indiesk** [comment]
Thanks! Hope it’s something easy to resolve.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmosorast** [comment]
Added these fields to the request for tickets in version 0.9.0
