### ISSUE TITLE
403 access_denied error - rate limiting?

### ISSUE THREAD

**Issue by trrad** [singer-io/tap-freshdesk#28]
When using the stitchdata freshdesk tap, I get this error for days on end. I suspect it has to do with rate limiting

> `Error making request to Freshdesk API: GET https://mysite.freshdesk.com/api/v2/tickets?updated_since=2018-09-27T22%3A30%3A25Z&order_type=asc&order_by=updated_at&per_page=100&include=requester%2Ccompany%2Cstats&page=1: [403 - b'{"code":"access_denied","message":"You are not authorized to perform this action."}']`

![image](https://user-images.githubusercontent.com/529676/50794088-0412d380-127f-11e9-84e2-2a7dcc6c45f4.png)

Attached is an example of it re-trying until it succeeds.

**Comment by KAllan357** [comment]
@trrad There is code that appears to be written to capture a rate limit: https://github.com/singer-io/tap-freshdesk/blob/master/tap_freshdesk/__init__.py#L56. Are you seeing that log message as well?
