### ISSUE TITLE
Stitch authentication failing

### ISSUE THREAD

**Issue by MVMT-BI** [singer-io/tap-freshdesk#6]
I setup the Freshdesk integration in Stitch and it looks like the initial data pull is failing - not sure if we're missing something but this is what I got from an email from Stitch:

We're encountering some errors with your freshdesk integration

Stitch is trying to replicate data from your freshdesk integration, and we're running into some trouble. 

Here is the error message we are encountering: 

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mvmtwatches.freshdesk.com/api/v2/tickets?updated_since=2014-01-01+00%3A00%3A00&order_type=asc&order_by=updated_at&page=1

If you can fix the issues for this integration, Stitch will automatically retry loading the data. If you're stuck, try checking out some of the more common issues and fixes in our help docs. Otherwise, log into your Stitch account and reach out to our support team. 

Let us know if you need help.

**Comment by briansloane** [comment]
This issue has been fixed. It was related to the way Stitch was running the tap internally.
